name: zmhr
markdown: redcarpet
highlighter: true
# url: http://zmhr.me
paginate: 8
permalink: pretty
description: zmhr
logo: logo.png
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

owner:
  name: Zahid Mahir
  avatar:
  email: zahid@zmhr.me
  twitter: "zahidmahir"
  github: "zahid"

google_analytics: UA-48961696-1
